import numpy as np

PHRASE_MAPPING = {
    '': '',

    "backward": "Bring your arm back",
    "backward down": "Lower your arm behind you",
    "backward left": "Move your arm back and toward your left side",
    "backward right": "Move your arm back and toward your right side",
    "backward up": "Raise your arm behind you",
    "down": "Lower your arm",
    "down forward": "Bring your arm down and forward",
    "down left": "Lower your arm toward your left side",
    "down right": "Lower your arm toward your right side",
    "forward": "Extend your arm forward",
    "forward left": "Reach forward and to the left",
    "forward right": "Reach forward and to the right",
    "forward up": "Lift your arm up and forward",
    "left": "Move your arm to the left",
    "left up": "Raise your arm to the left",
    "right": "Move your arm to the right",
    "right up": "Raise your arm to the right",
    "up": "Lift your arm up",

    "slightly backward": "Let's try moving your arm back just a bit, please",
    "slightly backward down": "Gently lower your arm behind you, just a little",
    "slightly backward left": "Move your arm back and slightly left, if you can",
    "slightly backward right": "A small movement back and to your right, please",
    "slightly backward up": "Let's try raising your arm behind you, just a touch",
    "slightly down": "Lower your arm just a bit, please",
    "slightly down forward": "Try bringing your arm down and forward slightly",
    "slightly down left": "Let's move your arm down and a little to the left",
    "slightly down right": "Can you lower your arm slightly toward the right?",
    "slightly forward": "Extend your arm forward just a bit",
    "slightly forward left": "Try reaching a little forward and left",
    "slightly forward right": "Reach just a bit forward and to the right",
    "slightly forward up": "Let's lift your arm slightly up and forward",
    "slightly left": "Ease your arm to the left",
    "slightly left up": "Raise your arm slightly up and left",
    "slightly right": "Shift your arm to the right",
    "slightly right up": "Let's try lifting your arm slightly up and right",
    "slightly up": "Raise your arm just a bit",

    "greatly backward": "I need you to move your arm back fully now",
    "greatly backward down": "Pull your arm back and down with more force",
    "greatly backward left": "Move your arm back and strongly to the left side",
    "greatly backward right": "Take your arm back and firmly to the right",
    "greatly backward up": "Push your arm back and up with full extension",
    "greatly down": "Lower your arm completely down now",
    "greatly down forward": "Bring your arm down and forward with strength",
    "greatly down left": "Move your arm down and firmly to the left",
    "greatly down right": "Pull your arm down and strongly to the right",
    "greatly forward": "Extend your arm forward fully now",
    "greatly forward left": "Reach forward and strongly to the left",
    "greatly forward right": "Push your arm forward and firmly to the right",
    "greatly forward up": "Lift your arm up and forward with full strength",
    "greatly left": "Move your arm firmly to the left",
    "greatly left up": "Raise your arm fully up and to the left",
    "greatly right": "Move your arm completely to the right",
    "greatly right up": "Lift your arm fully up and to the right",
    "greatly up": "Raise your arm up completely",

    "smoothly backward": "Glide your arm back with a fluid motion",
    "smoothly backward down": "Sweep your arm back and down in one motion",
    "smoothly backward left": "Flow your arm back and to the left side",
    "smoothly backward right": "Glide your arm back and toward the right",
    "smoothly backward up": "Let your arm float back and upward",
    "smoothly down": "Lower your arm in a continuous motion",
    "smoothly down forward": "Sweep your arm down and forward",
    "smoothly down left": "Glide your arm down toward the left",
    "smoothly down right": "Flow your arm down and to the right",
    "smoothly forward": "Extend your arm forward in one fluid motion",
    "smoothly forward left": "Sweep your arm forward and to the left",
    "smoothly forward right": "Glide your arm forward and right",
    "smoothly forward up": "Flow your arm up and forward",
    "smoothly left": "Sweep your arm to the left",
    "smoothly left up": "Glide your arm up and to the left",
    "smoothly right": "Flow your arm to the right",
    "smoothly right up": "Sweep your arm up and to the right",
    "smoothly up": "Let your arm rise smoothly",

    "sharply backward": "Snap your arm back with precision",
    "sharply backward down": "Pull your arm back and down quickly",
    "sharply backward left": "Move your arm back and left with precision",
    "sharply backward right": "Shift your arm back and right precisely",
    "sharply backward up": "Pull your arm back and up with quick movement",
    "sharply down": "Drop your arm down quickly",
    "sharply down forward": "Snap your arm down and forward",
    "sharply down left": "Move your arm down and left with precision",
    "sharply down right": "Shift your arm down and right precisely",
    "sharply forward": "Thrust your arm forward",
    "sharply forward left": "Jab your arm forward and left",
    "sharply forward right": "Push your arm forward and right quickly",
    "sharply forward up": "Snap your arm forward and up",
    "sharply left": "Cut your arm to the left",
    "sharply left up": "Snap your arm up and left",
    "sharply right": "Cut your arm to the right",
    "sharply right up": "Snap your arm up and right",
    "sharply up": "Lift your arm quickly",

    "slowly backward": "Ease your arm back with control",
    "slowly backward down": "Gradually move your arm back and down",
    "slowly backward left": "Carefully bring your arm back and left",
    "slowly backward right": "Deliberately move your arm back and right",
    "slowly backward up": "Gently raise your arm back and upward",
    "slowly down": "Lower your arm with control",
    "slowly down forward": "Gradually bring your arm down and forward",
    "slowly down left": "Ease your arm down and to the left",
    "slowly down right": "Carefully lower your arm to the right",
    "slowly forward": "Extend your arm forward with control",
    "slowly forward left": "Deliberately reach forward and left",
    "slowly forward right": "Carefully extend your arm forward and right",
    "slowly forward up": "Gradually lift your arm forward and up",
    "slowly left": "Ease your arm to the left",
    "slowly left up": "Slowly raise your arm left and upward",
    "slowly right": "Carefully move your arm to the right",
    "slowly right up": "Gradually lift your arm up and right",
    "slowly up": "Raise your arm upward with control",

    "quickly backward": "Swiftly pull your arm back",
    "quickly backward down": "Move your arm back and down rapidly",
    "quickly backward left": "Quickly shift your arm back and left",
    "quickly backward right": "Rapidly move your arm back and right",
    "quickly backward up": "Swiftly raise your arm back and up",
    "quickly down": "Drop your arm down fast",
    "quickly down forward": "Quickly bring your arm down and forward",
    "quickly down left": "Rapidly lower your arm to the left",
    "quickly down right": "Swiftly move your arm down and right",
    "quickly forward": "Push your arm forward quickly",
    "quickly forward left": "Rapidly extend your arm forward and left",
    "quickly forward right": "Swiftly move your arm forward and right",
    "quickly forward up": "Quickly lift your arm forward and up",
    "quickly left": "Swiftly move your arm left",
    "quickly left up": "Rapidly raise your arm left and up",
    "quickly right": "Move your arm right quickly",
    "quickly right up": "Swiftly lift your arm right and up",
    "quickly up": "Raise your arm up rapidly",

    "lightly backward": "Just barely move your arm back, nice and easy",
    "lightly backward down": "Gently guide your arm back and down",
    "lightly backward left": "With minimal effort, move your arm back and left",
    "lightly backward right": "Softly shift your arm back and right",
    "lightly backward up": "Gently raise your arm back and up",
    "lightly down": "Lower your arm with minimal tension",
    "lightly down forward": "Softly bring your arm down and forward",
    "lightly down left": "Gently guide your arm down and left",
    "lightly down right": "Easy now, lower your arm slightly right",
    "lightly forward": "Extend your arm forward with minimal effort",
    "lightly forward left": "Gently reach forward and left",
    "lightly forward right": "Softly extend your arm forward and right",
    "lightly forward up": "With minimal effort, bring your arm forward and up",
    "lightly left": "Move your arm left with gentle effort",
    "lightly left up": "Softly raise your arm left and up",
    "lightly right": "Gently shift your arm to the right",
    "lightly right up": "Easy now, lift your arm right and up",
    "lightly up": "Raise your arm with minimal tension",

    "significantly backward": "I need you to move your arm back considerably now",
    "significantly backward down": "Pull your arm back and down with strength",
    "significantly backward left": "Move your arm back and well to the left",
    "significantly backward right": "Bring your arm back and firmly to the right",
    "significantly backward up": "I need you to raise your arm back and up now",
    "significantly down": "Lower your arm substantially now",
    "significantly down forward": "Bring your arm down and forward with force",
    "significantly down left": "Move your arm down and well to the left",
    "significantly down right": "Pull your arm down and firmly to the right",
    "significantly forward": "Extend your arm forward considerably",
    "significantly forward left": "Reach forward and well to the left",
    "significantly forward right": "Push your arm forward and firmly right",
    "significantly forward up": "Lift your arm up and forward with purpose",
    "significantly left": "Move your arm firmly to the left",
    "significantly left up": "Raise your arm substantially up and left",
    "significantly right": "Move your arm firmly to the right",
    "significantly right up": "Lift your arm substantially up and right",
    "significantly up": "Raise your arm up considerably",

    "softly backward": "Let's ease your arm back gently",
    "softly backward down": "Tenderly move your arm back and down",
    "softly backward left": "Gently guide your arm back and left",
    "softly backward right": "Delicately move your arm back and right",
    "softly backward up": "Tenderly raise your arm back and up",
    "softly down": "Let's lower your arm gently",
    "softly down forward": "Delicately bring your arm down and forward",
    "softly down left": "Tenderly guide your arm down and left",
    "softly down right": "Gently move your arm down and right",
    "softly forward": "Let's extend your arm forward gently",
    "softly forward left": "Tenderly reach forward and left",
    "softly forward right": "Delicately extend your arm forward and right",
    "softly forward up": "Gently lift your arm forward and up",
    "softly left": "Let's move your arm left tenderly",
    "softly left up": "Delicately raise your arm left and up",
    "softly right": "Gently shift your arm to the right",
    "softly right up": "Tenderly lift your arm right and up",
    "softly up": "Let's raise your arm gently",

    "harshly backward": "Force your arm back now",
    "harshly backward down": "Drive your arm back and down firmly",
    "harshly backward left": "Push your arm back and left with power",
    "harshly backward right": "Drive your arm back and right with force",
    "harshly backward up": "Push your arm back and up firmly",
    "harshly down": "Force your arm down now",
    "harshly down forward": "Drive your arm down and forward firmly",
    "harshly down left": "Push your arm down and left with power",
    "harshly down right": "Drive your arm down and right with force",
    "harshly forward": "Push your arm forward with power",
    "harshly forward left": "Force your arm forward and left now",
    "harshly forward right": "Drive your arm forward and right firmly",
    "harshly forward up": "Push your arm forward and up with power",
    "harshly left": "Force your arm left now",
    "harshly left up": "Drive your arm left and up firmly",
    "harshly right": "Push your arm right with power",
    "harshly right up": "Force your arm right and up now",
    "harshly up": "Drive your arm up firmly",

    "gradually backward": "Begin moving your arm back, little by little",
    "gradually backward down": "Incrementally move your arm back and down",
    "gradually backward left": "Step by step, shift your arm back and left",
    "gradually backward right": "Progressively move your arm back and right",
    "gradually backward up": "Little by little, raise your arm back and up",
    "gradually down": "Lower your arm incrementally",
    "gradually down forward": "Step by step, bring your arm down and forward",
    "gradually down left": "Progressively lower your arm to the left",
    "gradually down right": "Incrementally move your arm down and right",
    "gradually forward": "Extend your arm forward little by little",
    "gradually forward left": "Step by step, reach forward and left",
    "gradually forward right": "Progressively extend your arm forward and right",
    "gradually forward up": "Incrementally lift your arm forward and up",
    "gradually left": "Move your arm left little by little",
    "gradually left up": "Step by step, raise your arm left and up",
    "gradually right": "Move your arm right incrementally",
    "gradually right up": "Little by little, lift your arm right and up",
    "gradually up": "Raise your arm up progressively",

    "immediately backward": "Move your arm back right now",
    "immediately backward down": "Pull your arm back and down at once",
    "immediately backward left": "Shift your arm back and left now",
    "immediately backward right": "Move your arm back and right this instant",
    "immediately backward up": "Raise your arm back and up right now",
    "immediately down": "Lower your arm down at once",
    "immediately down forward": "Bring your arm down and forward right now",
    "immediately down left": "Move your arm down and left this instant",
    "immediately down right": "Shift your arm down and right now",
    "immediately forward": "Extend your arm forward at once",
    "immediately forward left": "Reach forward and left right now",
    "immediately forward right": "Move your arm forward and right this instant",
    "immediately forward up": "Lift your arm forward and up now",
    "immediately left": "Move your arm left at once",
    "immediately left up": "Raise your arm left and up right now",
    "immediately right": "Shift your arm right this instant",
    "immediately right up": "Lift your arm right and up now",
    "immediately up": "Raise your arm up at once"
}

SIMPLE_PHRASE_MAPPING = {
    '': ["",],

    "backward": [
        "Bring your arm back",
        "Move your arm backward",
        "Pull your arm behind you"
    ],
    "backward down": [
        "Lower your arm behind you",
        "Move your arm back and down",
        "Drop your arm backward"
    ],
    "backward left": [
        "Move your arm back and left",
        "Bring your arm behind and left",
        "Pull your arm to the back-left"
    ],
    "backward right": [
        "Move your arm back and right",
        "Bring your arm behind and right",
        "Pull your arm to the back-right"
    ],
    "backward up": [
        "Raise your arm behind you",
        "Lift your arm back and up",
        "Reach upward behind you"
    ],
    "down": [
        "Lower your arm",
        "Drop your arm",
        "Move your arm downward"
    ],
    "down forward": [
        "Bring your arm down and forward",
        "Lower your arm in front",
        "Move your arm downward and forward"
    ],
    "down left": [
        "Lower your arm to the left",
        "Drop your arm left",
        "Move down toward the left"
    ],
    "down right": [
        "Lower your arm to the right",
        "Drop your arm right",
        "Move down toward the right"
    ],
    "forward": [
        "Extend your arm forward",
        "Reach out front",
        "Push your arm ahead"
    ],
    "forward left": [
        "Reach forward and left",
        "Move your arm ahead to the left",
        "Stretch your arm front-left"
    ],
    "forward right": [
        "Reach forward and right",
        "Move your arm ahead to the right",
        "Stretch your arm front-right"
    ],
    "forward up": [
        "Lift your arm up and forward",
        "Raise your arm diagonally forward",
        "Move your arm upward and ahead"
    ],
    "left": [
        "Move your arm to the left",
        "Extend your arm left",
        "Bring your arm leftward"
    ],
    "left up": [
        "Raise your arm to the left",
        "Lift your arm leftward",
        "Reach up and left"
    ],
    "right": [
        "Move your arm to the right",
        "Extend your arm right",
        "Bring your arm rightward"
    ],
    "right up": [
        "Raise your arm to the right",
        "Lift your arm rightward",
        "Reach up and right"
    ],
    "up": [
        "Lift your arm up",
        "Raise your arm",
        "Move your arm upward"
    ],
}

MEAN_WORDS_PER_PHRASE = np.mean(
    [len(PHRASE_MAPPING[phrase].split(' ')) for phrase in PHRASE_MAPPING])

MEAN_WORDS_PER_SIMPLE_PHRASE = np.mean(
    [len(phrase.split(' ')) for phrases in SIMPLE_PHRASE_MAPPING.values() for phrase in phrases])
